apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: minimal-httproute
spec:
  parentRefs:
  - name: minimal-gateway
    sectionName: http
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: log-output-svc
      port: 80
  - matches:
    - path:
        type: PathPrefix
        value: /pingpong
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
    backendRefs:
    - name: pingpong-svc
      port: 80