namespace: exercises

resources:
  - configmap-log-output.yaml
#  - deployment-log-output.yaml
  - rollout-log-output.yaml
#  - deployment-pingpong.yaml
  - rollout-pingpong.yaml
  - service-log-output.yaml
  - service-pingpong.yaml
#  - gateway.yaml
#  - httproute.yaml
  - ingress.yaml
  - middleware.yaml
  - statefulset-postgres.yaml
  - service-postgres.yaml
  - cpu-usage.yaml
