namespace: default

resources:
  - configmap-log-output.yaml
  - deployment-log-output.yaml
  - deployment-pingpong.yaml
  - service-log-output.yaml
  - service-pingpong.yaml
  - gateway.yaml
  - httproute.yaml
  - statefulset-postgres.yaml
  - service-postgres.yaml
