namespace: exercises

resources:
- configmap-log-output.yaml
- deployment-log-output.yaml
- deployment-pingpong.yaml
- service-log-output.yaml
- service-pingpong.yaml
- ingress.yaml
- middleware.yaml
