apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      env:
        - name: CACHE_DIR
          value: /app/.cache
      volumes:
        - name: cache-volume
          persistentVolumeClaim:
            claimName: image-cache-pvc
      containers:
        - name: webserver
          image: jjairola/webserver:latest
          env:
            - name: TODO_BACKEND_URL
              value: http://todo-backend-svc:2348
          volumeMounts:
            - mountPath: /app/.cache
              name: cache-volume