namespace: project

resources:
- deployment-todo-backend.yaml
- deployment-webserver.yaml
- service-todo-backend.yaml
- service-webserver.yaml
- ingress.yaml
- pvc.yaml
- statefulset-postgres.yaml
- service-postgres.yaml
- secret-postgres.yaml
- configmap-postgres.yaml
- cronjob-random-todo.yaml