namespace: project

resources:
- deployment-todo-backend.yaml
- deployment-webserver.yaml
- deployment-broadcaster.yaml
- service-todo-backend.yaml
- service-webserver.yaml
- service-broadcaster.yaml
- ingress.yaml
- pvc.yaml
- statefulset-postgres.yaml
- service-postgres.yaml
- secret-postgres.yaml
- secret-slack.yaml
- configmap-postgres.yaml
- cronjob-random-todo.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: jjairola/broadcaster
  newName: jjairola/broadcaster
  newTag: 0a6e86acb736ed4918cd83ba51ae4c7686b290af
- name: jjairola/todo-backend
  newName: jjairola/todo-backend
  newTag: 0a6e86acb736ed4918cd83ba51ae4c7686b290af
- name: jjairola/webserver
  newName: jjairola/webserver
  newTag: 0a6e86acb736ed4918cd83ba51ae4c7686b290af
