apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project

resources:
- deployment-todo-backend.yaml
- deployment-webserver.yaml
- deployment-broadcaster.yaml
- service-todo-backend.yaml
- service-webserver.yaml
- service-broadcaster.yaml
- ingress.yaml
- pvc.yaml
- statefulset-postgres.yaml
- service-postgres.yaml
- secret-postgres.yaml
- secret-slack.yaml
- configmap-postgres.yaml
- cronjob-random-todo.yaml
images:
- name: jjairola/broadcaster
  newName: jjairola/broadcaster
  newTag: 50b6b466f92265fd796f2b3dee3ad4411d6440ec
- name: jjairola/todo-backend
  newName: jjairola/todo-backend
  newTag: 50b6b466f92265fd796f2b3dee3ad4411d6440ec
- name: jjairola/webserver
  newName: jjairola/webserver
  newTag: 50b6b466f92265fd796f2b3dee3ad4411d6440ec
