apiVersion: v1
kind: Secret
metadata:
  name: slack-secret
type: Opaque
data:
  # You can encode it with: echo -n "https://hooks.slack.com/services/YOUR/WEBHOOK/URL" | base64
  webhook_url: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDA5S1NUR0VQU1QvQjA5U1k5MEVCTlgvS3dnV09EUVk1Tjdzc1ZQT3JFZ2c1YTY4Cg==