apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./../base
patches:
- path: deployment-broadcaster.yaml
- path: cronjob-backup.yaml
namePrefix: prod-
images:
- name: jjairola/broadcaster
  newName: jjairola/broadcaster
  newTag: 85a6d215ba84c4e973906712f5d061a71c687b2f
- name: jjairola/todo-backend
  newName: jjairola/todo-backend
  newTag: 85a6d215ba84c4e973906712f5d061a71c687b2f
- name: jjairola/webserver
  newName: jjairola/webserver
  newTag: 85a6d215ba84c4e973906712f5d061a71c687b2f
