apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./../base
patches:
- path: deployment-broadcaster.yaml
- path: cronjob-backup.yaml
namePrefix: prod-
images:
- name: jjairola/broadcaster
  newName: jjairola/broadcaster
  newTag: 8ce544ee73943288bf30a1b1ccf14317177621dd
- name: jjairola/todo-backend
  newName: jjairola/todo-backend
  newTag: 8ce544ee73943288bf30a1b1ccf14317177621dd
- name: jjairola/webserver
  newName: jjairola/webserver
  newTag: 8ce544ee73943288bf30a1b1ccf14317177621dd
