apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./../base
namePrefix: prod-
images:
- name: jjairola/broadcaster
  newName: jjairola/broadcaster
  newTag: 43fcf94642ef0f61d8688dc1c8c62d93a714ffea
- name: jjairola/todo-backend
  newName: jjairola/todo-backend
  newTag: 43fcf94642ef0f61d8688dc1c8c62d93a714ffea
- name: jjairola/webserver
  newName: jjairola/webserver
  newTag: 43fcf94642ef0f61d8688dc1c8c62d93a714ffea
