apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./../base
namePrefix: prod-
images:
- name: jjairola/broadcaster
  newName: jjairola/broadcaster
  newTag: 274697dadd1e246f3dccc27c61974be4c6de3a31
- name: jjairola/todo-backend
  newName: jjairola/todo-backend
  newTag: 274697dadd1e246f3dccc27c61974be4c6de3a31
- name: jjairola/webserver
  newName: jjairola/webserver
  newTag: 274697dadd1e246f3dccc27c61974be4c6de3a31
