apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./../base
namePrefix: prod-
images:
- name: jjairola/broadcaster
  newName: jjairola/broadcaster
  newTag: 604e2074af1351e29ff9404a0fe7391343edf94d
- name: jjairola/todo-backend
  newName: jjairola/todo-backend
  newTag: 604e2074af1351e29ff9404a0fe7391343edf94d
- name: jjairola/webserver
  newName: jjairola/webserver
  newTag: 604e2074af1351e29ff9404a0fe7391343edf94d
