apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./../base
namePrefix: prod-
images:
- name: jjairola/broadcaster
  newName: jjairola/broadcaster
  newTag: 95fac6f0ba9df5fe09eef42c112ca85094ce8236
- name: jjairola/todo-backend
  newName: jjairola/todo-backend
  newTag: 95fac6f0ba9df5fe09eef42c112ca85094ce8236
- name: jjairola/webserver
  newName: jjairola/webserver
  newTag: 95fac6f0ba9df5fe09eef42c112ca85094ce8236
