name: Build and publish exercises

on:
  push:
    paths:
      - 'exercises/**'

jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish log_output
        run: |-
          docker build --tag "jjairola/log_output:$GITHUB_SHA" exercises/log_output
          docker push "jjairola/log_output:$GITHUB_SHA"

      - name: Build and publish pingpong
        run: |-
          docker build --tag "jjairola/pingpong:$GITHUB_SHA" exercises/pingpong
          docker push "jjairola/pingpong:$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update kustomization images
        run: |-
          cd exercises/manifests
          kustomize edit set image jjairola/log_output=jjairola/log_output:$GITHUB_SHA
          kustomize edit set image jjairola/pingpong=jjairola/pingpong:$GITHUB_SHA

      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: 'exercises/manifests/kustomization.yaml'
          message: New version released ${{ github.sha }}