name: Build and publish project

on:
  push:
    branches:
      - main
    paths:
      - 'project/**'
    tags:
      - '*'
      
jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish broadcaster
        run: |-
          docker build --tag "jjairola/broadcaster:$GITHUB_SHA" project/broadcaster
          docker push "jjairola/broadcaster:$GITHUB_SHA"

      - name: Build and publish todo-backend
        run: |-
          docker build --tag "jjairola/todo-backend:$GITHUB_SHA" project/todo-backend
          docker push "jjairola/todo-backend:$GITHUB_SHA"

      - name: Build and publish webserver
        run: |-
          docker build --tag "jjairola/webserver:$GITHUB_SHA" project/webserver
          docker push "jjairola/webserver:$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update kustomization images
        run: |-
          cd project/manifests/base
          kustomize edit set image jjairola/broadcaster=jjairola/broadcaster:$GITHUB_SHA
          kustomize edit set image jjairola/todo-backend=jjairola/todo-backend:$GITHUB_SHA
          kustomize edit set image jjairola/webserver=jjairola/webserver:$GITHUB_SHA

      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: 'project/manifests/base/kustomization.yaml'
          message: New version released ${{ github.sha }}

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build-publish
    if: github.ref == 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Deploy to staging
        run: |
          kubectl config set-context --current --namespace=staging
          kustomize build project/manifests/staging | kubectl apply -f -

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build-publish
    if: github.ref_type == 'tag'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Deploy to production
        run: |
          kubectl config set-context --current --namespace=production
          kustomize build project/manifests/prod | kubectl apply -f -